### PR TITLE
Use smart 'add' function

### PR DESCRIPTION
**Pull request by Mudrekh**
@hawkeye64 Hello, I'm looking for an onvif project to build on and stumbled across your module and gave it a test spin. My initial tests were promising, so I figured I'd give a PR a shot. 

This PR aims to simplify the module loading in Camera.js. The switch is a little overkill for something that is quite repetitive. Its nice to see that all your modules follow the same syntactic style!

### CODE REVIEW

**Comment by Mudrekh** [comment]
@hawkeye64 Looks like this PR failed at the coveralls step. Would love your input on that since I am not too familar with CircleCI/Coveralls

**Comment by hawkeye64** [comment]
I was such a noob when I wrote this. My first package. And, we still use it at work.
Now, when I look at it, I'd say what you did was definitely on the was of optimization and perf, but can be taken a step further.
Totally agree that the switch statement should disappear. 
Instead, create an object with keys from the switch statement
```js
let actions = {
  snapshot: {
    init () {
        if (!this.snapshot) {
          const Snapshot = require('./utils/snapshot')
          this.snapshot = new Snapshot()
          const defaultProfile = this.getDefaultProfile()
          if (defaultProfile) {
            const snapshotUri = defaultProfile.SnapshotUri.Uri
            this.snapshot.init(snapshotUri, this.username, this.password)
          }
        }
    }
  },
  media: {
    init () {
        if (!this.media) {
          const Media = require('./modules/media')
          this.media = new Media()
          this.media.init(this.timeDiff, this.serviceAddress, this.username, this.password)
        }
    }
  }
  // and so on
}
```
then,
```js
add (name) {
  if (this.actions[name]) {
    this.actions[name].init()
  } else {
    // error handling
}
```
Do you want to try again? Maybe a different branch since this one is "polluted" now.

**Comment by Mudrekh** [comment]
Sorry, what do you mean by a step further? And what do you mean by polluted?

**Comment by hawkeye64** [comment]
By "polluted" I mean, if you make more, radical changes, that are not in step with the current branch, then the PR looks messy.
By "step further" I mean do the code I suggested above. Or, wait until Monday when I have PTZ cameras available I can test with and I'll do it.

**Comment by hawkeye64** [comment]
Also, not sure why the Coveralls failed. It may only work for me. I am not sure.

```bash
/home/circleci/onvif-nvt/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by Mudrekh** [comment]
So you would want to still define a block/ funciton per module instead of using the string to require it? As for polluted... I can always just force push over it. Its just a fork.

**Pull request merged**
